### ISSUE TITLE
G to open the Wagon Menu,

### ISSUE THREAD

**Issue by EarthWst** [BryceCanyonCounty/bcc-wagons#26]
When I press G to open the Wagon Menu, nothing happens, and my game screen freezes.
I can't move or do anything. Please tell me how to fix it.

**Comment by JusCampin** [comment]
Install feather-menu.zip from here:
https://github.com/FeatherFramework/feather-menu/releases

![image](https://github.com/user-attachments/assets/5ad275bb-bb4e-4dca-9fbc-9e6e9cf1a253)

Make sure to ensure it before all bcc-scripts.
